main: me.mrletsplay.skyblock.Skyblock
name: LP-Skyblock
version: 1.0
author: MrLetsplay2003
api-version: 1.13
softdepend: [MrCore_BukkitImpl, BentoBox]

commands:
  lpskyblock:
  composter:
  generator:
  biomes:
  level:
  challenges:
  visit:
  visit-settings:
